import Vue from 'vue';
import {
  Vuetify,
  VApp,
  VDataTable,
  VFooter,
  VList,
  VNavigationDrawer,
  VCard,
  VSnackbar,
  VTabs,
  VCarousel,
  VParallax,
  VAvatar,
  VExpansionPanel,
  VJumbotron,
  VForm,
  VBtn,
  VIcon,
  VGrid,
  VBadge,
  VSelect,
  VRadioGroup,
  VToolbar,
  transitions,
  VSubheader,
  VTextField,
  VChip,
  VStepper,
  VDivider,
  VMenu,
  VRangeSlider,
  VCheckbox,
  VAutocomplete,
  VOverflowBtn,
} from 'vuetify';

Vue.use(Vuetify, {
  theme: {},
  components: {
    VApp,
    VRangeSlider,
    VRadioGroup,
    VDataTable,
    VAvatar,
    VSelect,
    VCarousel,
    VSnackbar,
    VExpansionPanel,
    VParallax,
    VJumbotron,
    VBadge,
    VNavigationDrawer,
    VFooter,
    VList,
    VTabs,
    VChip,
    VBtn,
    VCard,
    VForm,
    VIcon,
    VGrid,
    VToolbar,
    transitions,
    VSubheader,
    VTextField,
    VStepper,
    VDivider,
    VMenu,
    VCheckbox,
    VAutocomplete
} from 'vuetify'

Vue.use(Vuetify, {
    theme: {

    },
    components: {
        VApp,
        VRadioGroup,
        VDataTable,
        VAvatar,
        VSelect,
        VCarousel,
        VSnackbar,
        VExpansionPanel,
        VParallax,
        VJumbotron,
        VBadge,
        VNavigationDrawer,
        VFooter,
        VList,
        VTabs,
        VBtn,
        VCard,
        VForm,
        VIcon,
        VGrid,
        VToolbar,
        transitions,
        VSubheader,
        VTextField,
        VStepper,
        VDivider,
        VMenu,
        VCheckbox,
        VAutocomplete
    }
})
